name: Windows - Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Windows - Build & Test
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [ Debug, Release ]
        std: [ 23 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC dev environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install recent CMake + Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "4.3.0"

      - name: Configure CMake
        run: >
          cmake -B ${{runner.workspace}}\Build
          -G Ninja
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_CXX_STANDARD=${{ matrix.std }}
          -DCMAKE_CXX_STANDARD_REQUIRED=ON
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{runner.workspace}}\Build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{runner.workspace}}\Build\tests
        run: ctest --output-on-failure

      - name: Test2
        run: ${{runner.workspace}}/Build/tests/FawnAlgebra_test
